services:
  db:
    container_name: goddb
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_DATABASE=godinfo
    volumes:
      - ./service1/database:/docker-entrypoint-initdb.d
    ports:
      - "2000:3306"
    networks:
      - godnet

  service1:
    container_name: service1
    build:
      context: ./service1
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:xxxx@db:3306/godinfo
    networks:
      - godnet

  service2:
    container_name: service2
    build:
      context: ./service2
    ports:
      - "9000:9000"
    networks:
      - godnet

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5000:3000"
    depends_on:
      - service1
      - service2
    environment:
      - SERVICE1_URL=http://service1:8000
      - SERVICE2_URL=http://service2:9000
    networks:
      - godnet

networks:
  godnet:
    driver: bridge
